baseURL = '/'
languageCode = 'en-us'
title = 'Kirk Agbenyegah'
theme = 'ink-free'
copyright = "Â© Kirk Agbenyegah"
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Shipping software, one hack at a time."

	# Optional 64x64 avatar image.
	avatar = "https://raw.githubusercontent.com/savekirk/dela.github.io/main/assets/images/me.jpg"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents
	toc = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	#footers = [ 
	#	
	#]

	# Github base url
	# github = "https://github.com/savekirk/dela.github.io"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

# [[menu.main]]
# name = "All posts"
# url = "/posts"
# weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/savekirk/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = "table"
    noClasses = false
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
